# Generated by Django 4.2.11 on 2025-10-29 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_category_project_delete_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='project',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
    ]
